# Generated by Django 3.0.5 on 2021-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_autotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(max_length=124, verbose_name='Position')),
                ('firstName', models.CharField(max_length=124)),
                ('lastName', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=15)),
                ('employment', models.CharField(max_length=124)),
                ('experience', models.CharField(max_length=124)),
                ('date_applied', models.DateField(auto_now_add=True, null=True)),
                ('letter', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=124)),
                ('subject', models.CharField(blank=True, max_length=12, null=True)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='autotest',
        ),
        migrations.DeleteModel(
            name='newmodeltest',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
